DavinaNaran22/IntroGame

Assets/Prefabs/Interior.prefab, Assets/Prefabs/Interior.prefab.meta, Assets/Prefabs/Player.prefab, Assets/Scenes/Main.unity
Sort of fixes the clipping issue (but not really)
=> Fix clipping

Assets/Prefabs/Interior/NewInterior.prefab, Assets/Prefabs/Interior/OxygenTank.prefab, Assets/Scenes/Interior.unity, Assets/Scenes/landscape.unity, Assets/Scripts/GameManager.cs, Assets/Scripts/GameManager.cs.meta, Assets/Scripts/Keypad.cs, Assets/Scripts/KeypadDoor.cs, Assets/Scripts/KeypadDoor.cs.meta, Assets/Scripts/PlayerMovement.cs, Assets/Scripts/PlayerNearText.cs, Assets/Scripts/PlayerSceneTransition.cs, Assets/Scripts/Singleton.cs, Assets/Scripts/TeleportCockpit.cs
Start game from landscape to test features
=> Improvements final

Assets/Prefabs/UI/ExitButton.prefab, Assets/Prefabs/UI/ExitButton.prefab.meta, Assets/Prefabs/UI/GreenSubtitleBox.prefab, Assets/Prefabs/UI/GreenSubtitleBox.prefab.meta, Assets/Prefabs/UI/PlayerHealthBar.prefab, Assets/Prefabs/UI/PlayerHealthBar.prefab.meta, Assets/Prefabs/UI/UIManager.prefab, Assets/Scenes/Interior.unity, Assets/Scenes/Main.unity, Assets/Scenes/landscape.unity, Assets/Scripts/ColourDropdown.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/PlayerHealth.cs, Assets/Scripts/RepairTask1.cs, ProjectSettings/TagManager.asset
- Change Green images to Yellow
- Fix dropdown not showing selected colour mode
- Get rid of double save button in landscape :)
=> More Colourblind edits

Assets/Scenes/Interior.unity, Assets/Scripts/PlayerNearText.cs
=> Noor latest

Assets/Prefabs/UI/UIManager.prefab, Assets/Scripts/EnterAlienArea2.cs, Assets/Scripts/EnterAlienArea2.cs.meta, Assets/Scripts/GreenAlienBehaviour.cs, Assets/Scripts/RepairTask1.cs, Assets/Scripts/RepairTask2.cs, Assets/Scripts/RepairTask2.cs.meta
Positioned next scene - aliens and boulder
New script for two bounary areas - barrier to stop user from getting to close to take picture, another barrier for fighting
Alien paces around
Set up alien for scene 3 on bridge - health for alien goes down by 20% so harder
Scene 3 alien paceing increased
=> Davina scenes

Assets/Control_panel.cs, Assets/Interior_Manager.cs, Assets/Scenes/Interior.unity, Assets/Storage_Scene.cs, mono_crash.32c9db773e.0.json
pls let me know the parts of the ship that need to be fixed to add to status !
=> REDONE interior scenes

Assets/Materials/green-light.mat, Assets/Materials/green-light.mat.meta, Assets/Scenes/Game.unity, Assets/Scripts/Wing.cs, Assets/Scripts/WingBarrier.cs, Assets/Storage_Scene.cs, Assets/WireRepair.cs, Assets/win_message.cs, Assets/wing_attached.cs
- conflicts with destory script
- added green highlight on wing and place to place the wing
- wire game added
=> Added message/game transition

Assets/Scenes/Interior.unity, Assets/Scripts/ColourDropdown.cs, Assets/Scripts/KeypadDoor.cs, Assets/Scripts/Pause.cs, Assets/Scripts/Singleton.cs
Fix keypad not showing and prevent player from moving + looking
=> Fix keypad causing pause bug

Assets/Scripts/Task4Clue.cs, Assets/Scripts/Task4Clue.cs.meta
Dialogue for boulder
Logic to equip clue for scene 4
=> Added boulder equipping logic for scene 4

Assets/Scenes/CaveScene.unity, Assets/Scenes/Interior.unity, Assets/Scripts/CaveAlienMoving.cs, Assets/Scripts/CaveCamRestrict.cs, Assets/Scripts/CaveScene.cs, Assets/Scripts/EnterAlienArea3.cs, Assets/Scripts/EnterAlienArea4.cs, Assets/Scripts/RhinoAlienBehaviour.cs
Fix collider not disabling in scene 3
=> Davina scenes um

Assets/Prefabs/UI/WinScreen.prefab, Assets/Prefabs/UI/WinScreen.prefab.meta, Assets/Scenes/Death.unity, Assets/Scenes/Death.unity.meta, Assets/Scenes/Win.unity, Assets/Scenes/Win.unity.meta, Assets/Scripts/OxygenDisplay.cs, Assets/Scripts/PlayerHealth.cs, Assets/Scripts/PlayerSceneTransition.cs, Assets/Scripts/mainmenu.cs, ProjectSettings/EditorBuildSettings.asset
Also changed PlayerSceneTransition scene loading to being asynchronous
=> Add menus when player wins and dies

Assets/Control_panel.cs, Assets/Scenes/Interior.unity, Assets/Scripts/Ending.cs, Assets/Scripts/Ending.cs.meta
Dialogue and button ready for ending scene - just need to link it with previous scene and end menu
=> Davina scenes um2

Assets/Scenes/Interior.unity, Assets/Scripts/PlayerNearEquipable.cs, Assets/Scripts/PlayerNearEquipable.cs.meta, Assets/Scripts/PlayerNearText.cs
- Equipping object has same radius as equip text
- Player loads in landscape after wire game complete (although wrong dialouge might show?)
=> Fix equip text and loading landscape after game

Assets/Scenes/Game.unity, Assets/Scripts/WireRepair.cs, Assets/Scripts/wing_attached.cs
Scene 4 text logic finished and working
=> Text for scene 4 finished

Assets/Materials/green-light.mat, Assets/Scripts/RepairTask4.cs, Assets/Scripts/StartClue.cs, Assets/Scripts/StartClue.cs.meta, Assets/Scripts/Task4Clue.cs, Assets/Scripts/WireRepair.cs
=> Link scene 4 with clue

Assets/Scripts/KeypadDoor.cs, Assets/Scripts/LightningController.cs, Assets/Scripts/PlayerNearText.cs
Hover text doesn't change back to 'enter keycode'
Lightning controller active in all scenes
=> Fix hover text and lightning controller

Assets/Scenes/CaveScene.unity, Assets/Scripts/CaveAlienMoving.cs
Cave aliens no longer walking through walls
=> Sorting out aliens walking through walls in cave

Assets/Scenes/Interior.unity, Assets/Scripts/GameManager.cs, Assets/Scripts/WeatherManager.cs
Otherwise it would deactive itself :)
=> Fix weather not activating

Assets/Scenes/Game.unity, Assets/Scripts/Clue_drag.cs, Assets/Scripts/Control_panel.cs, Assets/Scripts/Interior_Manager.cs, Assets/Scripts/Puzzle_repair.cs, Assets/Scripts/Scene5.cs, Assets/Scripts/Storage_Scene.cs, Assets/Scripts/WireRepair.cs, Assets/Scripts/puzzle.cs, Assets/Scripts/win_message.cs, Assets/Scripts/wing_attached.cs
- found scripts i no longer use ( i will delete) commented the scripts
=> Code is commented

Assets/Prefabs/UI/UIManager.prefab, Assets/Scenes/Interior.unity, Assets/Scripts/Control_panel.cs, Assets/Scripts/Interior_Manager.cs, Assets/Scripts/Keypad.cs, Assets/Scripts/PanelManager.cs, Assets/Scripts/Storage_Scene.cs
attempt at progress bar - bugs with interior tasks to fix first
=> Attempt of progress bar with interior tasks

Assets/Scenes/Interior.unity, Assets/Scripts/QuantityManager.cs
toolboxImage  inactive at first then active when all tools equipped
=> tools equipped

Assets/Scenes/Interior.unity, Assets/Scripts/EquipManager.cs, Assets/Scripts/EquipManager.cs.meta, Assets/Scripts/EquipObject.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/PlayerNearEquipable.cs, Assets/Scripts/Scene5.cs, Assets/Scripts/Storage_Scene.cs
Objects which get equipped no longer show between scenes
=> Equip persistence
